name: chat_app
description: "A modern, elegant desktop chat application inspired by WhatsApp Web."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  emoji_picker_flutter: ^2.2.0
  flutter_svg: ^2.0.10+1

  # State Management
  get: ^4.6.6

  # File & Image Handling
  file_picker: ^8.0.6
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.3

  # API & Networking
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  
  # WebSocket & Real-time
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  
  # Local Storage & Database
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Local Notifications (no Firebase needed)
  flutter_local_notifications: ^16.3.2
  
  # Security & Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # File Upload & Download
  path_provider: ^2.1.2
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700